[0;33m--- esp-idf-monitor 1.3.2 on /dev/cu.usbserial-A50285BI 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ashishsaini/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/Users/ashishsaini/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/esp_idf_monitor/base/serial_reader.py", line 55, in run
    self.serial.open()
  File "/Users/ashishsaini/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/serial/serialposix.py", line 332, in open
    self._reconfigure_port(force_update=True)
  File "/Users/ashishsaini/.espressif/python_env/idf5.2_py3.9_env/lib/python3.9/site-packages/serial/serialposix.py", line 517, in _reconfigure_port
    termios.tcsetattr(
termios.error: (22, 'Invalid argument')
[0m
